# -*- coding: utf-8 -*-
"""Assignment Statements.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I7dm1ksChmELLAqcbSVRM2ofkTDNwVA_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

starting_date = '20160701'
sample_numpy_data = np.array(np.arange(24)).reshape((6,4))
dates_index = pd.date_range(starting_date, periods=6)
sample_df = pd.DataFrame(sample_numpy_data, index=dates_index, columns=list('ABCD'))
sample_df

sample_df_2 = sample_df.copy()
sample_df_2['Fruits'] = ['apple', 'orange','banana','strawberry','blueberry','pineapple']
sample_df_2

pd.date_range(starting_date, periods=6)

pd.Series([1,2,3,4,5,6], index=pd.date_range(starting_date, periods=6))

sample_series = pd.Series([1,2,3,4,5,6], index=pd.date_range(starting_date, periods=6))
sample_df_2['Extra Data'] = sample_series *3 +1
sample_df_2

sample_df_2.at[dates_index[3],'Fruits'] = 'pear'
sample_df_2

sample_df_2.iat[3,2] = 4444
sample_df_2

second_numpy_array = np.array(np.arange(len(sample_df_2)))  *100 + 7
second_numpy_array

sample_df_2['G'] = second_numpy_array
sample_df_2



