# -*- coding: utf-8 -*-
"""Object creation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UcdGUSeBFt3WHMwAkn7eeiIzXR2OIjFi
"""

import pandas as pd
import numpy as np

my_series = pd.Series([1,3,5,np.nan,6,8])
my_series

my_dates_index = pd.date_range('20160101', periods=6)
my_dates_index

sample_numpy_data = np.array(np.arange(24)).reshape((6,4))
sample_numpy_data

sample_df = pd.DataFrame(sample_numpy_data, index=my_dates_index, columns=list('ABCD'))
sample_df

df_from_dictionary = pd.DataFrame({
                         'float' : 1.,
                         'time' : pd.date_range('20160101', periods=4),
                         'series' : pd.Series(1,index=list(range(4)),dtype='float32'),
                         'array' : np.array([3] * 4,dtype='int32'),
                         'categories' : pd.Categorical(["test","train","taxes","tools"]),
                         'dull' : 'uwu data'
                      })
df_from_dictionary

df_from_dictionary.dtypes

sample_df.head(3)

sample_df.tail(2)

sample_df.values

sample_df.index

sample_df.columns

#describe(): a quick statistical summary
sample_df.describe()

pd.set_option('display.precision', 1)

sample_df.describe()

#transpose
sample_df.T

sample_df.sort_index(axis=1, ascending=False)

sample_df.sort_values(by='B', ascending=False)