# -*- coding: utf-8 -*-
"""Remote Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lm9f175ui_tjH5jYmkLmEXFmQaNhazn0
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import datetime
from pandas_datareader import data, wb

#Yahoo finance
start = datetime.datetime(2010, 1, 1)
end = datetime.datetime(2019, 1, 15)
yahoo_df = data.DataReader("F", 'yahoo', start, end)
yahoo_df.plot()

#Google
start = datetime.datetime(2010, 1, 1)
end = datetime.datetime(2019, 1, 15)
google_df = data.DataReader("F", 'google', start, end)
google_df.plot()

google_series = pd.Series(google_df.index)