# -*- coding: utf-8 -*-
"""Selection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E_8jC1zcTs7uKuNXIgv1Eb7xCaF4Qc9_
"""

import pandas as pd
import numpy as np

sample_numpy_data = np.array(np.arange(24)).reshape((6,4))
dates_index = pd.date_range('20160101', periods=6)
sample_df = pd.DataFrame(sample_numpy_data, index=dates_index, columns=list('ABCD'))
sample_df

sample_df['C']

sample_df[1:4]

sample_df['2016-01-02':'2016-01-04']

sample_df.loc[dates_index[1:3]]

sample_df.loc[:,['A','B']]

sample_df.loc['2016-01-01':'2016-01-03',['A','C']]

sample_df.loc['2016-01-03',['D','B']]

sample_df.loc['2016-01-03',['D','B']] [0] * 4

sample_df.loc[dates_index[2], 'C']

sample_numpy_data[3]

sample_df.iloc[3]

sample_df.iloc[1:3, 2:4]

sample_df.iloc[[0,1,3], [0,2]]

sample_df.iloc[1:3,:]

sample_df.iloc[:, 1:3]

sample_df.C >= 14

sample_df[sample_df >= 11]

sample_df_2 = sample_df.copy()
sample_df_2['Fruits'] = ['apple', 'orange','banana','strawberry','blueberry','pineapple']
sample_df_2

sample_df_2[sample_df_2['Fruits'].isin(['banana','pineapple', 'smoothy'])]

